import os
import sys
import time
# pyrefly: ignore [missing-import]
import httpx

# Ensure backend/app and backend are in sys.path
test_dir = os.path.dirname(os.path.abspath(__file__))
backend_dir = os.path.dirname(test_dir)
app_dir = os.path.join(backend_dir, "app")
for p in [app_dir, backend_dir]:
    if p not in sys.path:
        sys.path.insert(0, p)

def test_demo_readiness():
    print("==================================================")
    print("STARTING E2E DEMO READINESS CHECKLIST VERIFICATION")
    print("==================================================")
    
    # Base URL for the running FastAPI server with extended timeout for model loading
    client = httpx.Client(base_url="http://127.0.0.1:8000", timeout=120.0)
    
    # 1. Health check
    print("\n[CHECK 1] Verifying Backend API Health Status...")
    res = client.get("/health")
    assert res.status_code == 200, "Health check failed"
    data = res.json()
    assert data["status"] == "healthy"
    print(" -> PASSED: Backend is running and healthy!")

    # 2. Document Analysis
    print("\n[CHECK 2] Verifying Document Analysis...")
    sample_text = (
        "EMPLOYEE LEAVE POLICY\n\n"
        "1. Annual Leave\n"
        "Employees are entitled to 20 days of annual leave per calendar year.\n"
        "Leave must be requested and approved at least 2 weeks in advance.\n\n"
        "2. Sick Leave\n"
        "Paid sick leave is provided up to 10 days per year for illnesses.\n"
        "A medical certificate is required for absences exceeding 3 consecutive days.\n"
    )
    res = client.post("/document/analyze", json={"text": sample_text})
    assert res.status_code == 200, f"Document analysis failed with status: {res.status_code}"
    analysis = res.json()
    assert "document_type" in analysis
    assert "avg_sentence_length" in analysis
    print(f" -> PASSED: Document analyzed successfully. Category detected: {analysis['document_type']}")

    # 3. Fixed-Size Chunking
    print("\n[CHECK 3] Verifying Fixed-Size Chunking strategy...")
    payload = {"text": sample_text, "chunk_size": 100, "chunk_overlap": 20}
    res = client.post("/chunk/fixed", json=payload)
    assert res.status_code == 200, f"Fixed chunker failed: {res.status_code}"
    chunks = res.json()["chunks"]
    assert len(chunks) > 0, "No chunks generated by fixed chunker"
    print(f" -> PASSED: Fixed chunking generated {len(chunks)} chunks.")

    # 4. Recursive Character Chunking
    print("\n[CHECK 4] Verifying Recursive Character Chunking strategy...")
    payload = {"text": sample_text, "chunk_size": 100, "chunk_overlap": 20}
    res = client.post("/chunk/recursive", json=payload)
    assert res.status_code == 200, f"Recursive chunker failed: {res.status_code}"
    res_data = res.json()
    assert len(res_data["chunks"]) > 0, "No chunks generated by recursive chunker"
    assert "hierarchy" in res_data, "Hierarchy tree missing from recursive response"
    print(f" -> PASSED: Recursive chunking generated {len(res_data['chunks'])} chunks with sitemap tree.")

    # 5. Document-Structure Aware Chunking
    print("\n[CHECK 5] Verifying Document-Structure Aware Chunking strategy...")
    payload = {"text": sample_text}
    res = client.post("/chunk/document", json=payload)
    assert res.status_code == 200, f"Document chunker failed: {res.status_code}"
    chunks = res.json()["chunks"]
    assert len(chunks) > 0, "No chunks generated by document chunker"
    print(f" -> PASSED: Structural chunking split document into {len(chunks)} section segments.")

    # 6. Semantic Similarity Chunking (with cache hit check)
    print("\n[CHECK 6] Verifying Semantic Similarity Chunking strategy...")
    payload = {"text": sample_text, "threshold": 0.5}
    
    # First run (should encode sentences)
    t0 = time.perf_counter()
    res1 = client.post("/chunk/semantic", json=payload)
    t1 = time.perf_counter()
    duration1 = (t1 - t0) * 1000
    
    assert res1.status_code == 200, f"Semantic chunker failed: {res1.status_code}"
    chunks1 = res1.json()["chunks"]
    assert len(chunks1) > 0, "No chunks generated by semantic chunker"
    assert "topic" in chunks1[0], "No topic keywords extracted for semantic chunks"
    
    # Second run (should hit cache)
    t2 = time.perf_counter()
    res2 = client.post("/chunk/semantic", json=payload)
    t3 = time.perf_counter()
    duration2 = (t3 - t2) * 1000
    
    assert res2.status_code == 200
    print(f" -> First run duration: {duration1:.2f} ms")
    print(f" -> Second run duration (cache hit): {duration2:.2f} ms")
    assert duration2 < duration1 or duration2 < 100.0, "Cache hit must be near instantaneous"
    print(f" -> PASSED: Semantic chunking generated {len(chunks1)} chunks. Caching verified successfully!")

    # 7. Query-Aware Chunking
    print("\n[CHECK 7] Verifying Query-Aware Chunking strategy...")
    payload = {
        "text": sample_text,
        "query": "annual leave policy allowance",
        "chunk_size": 100,
        "chunk_overlap": 20
    }
    res = client.post("/chunk/query-aware", json=payload)
    assert res.status_code == 200, f"Query-aware chunker failed: {res.status_code}"
    chunks = res.json()["chunks"]
    assert len(chunks) > 0
    assert "score" in chunks[0]
    # Check that it's sorted by relevance
    scores = [c["score"] for c in chunks]
    assert scores == sorted(scores, reverse=True), "Query-aware chunks must be sorted by similarity score"
    print(f" -> PASSED: Query-aware chunking generated and ranked {len(chunks)} chunks.")

    # 8. Metadata-Aware Chunking & Heuristics
    print("\n[CHECK 8] Verifying Metadata-Aware Chunking strategy...")
    payload = {
        "text": sample_text,
        "chunk_size": 150,
        "chunk_overlap": 20,
        "auto_discover": True
    }
    res = client.post("/chunk/metadata", json=payload)
    assert res.status_code == 200, f"Metadata chunker failed: {res.status_code}"
    res_data = res.json()
    chunks = res_data["chunks"]
    assert "metadata" in chunks[0], "No metadata attached to chunks"
    assert "boundary_reason" in chunks[0], "Boundary reason missing from chunk"
    assert "timeline" in res_data, "Timeline missing from response"
    print(f" -> PASSED: Metadata chunking detected properties and injected context tags.")

    # 9. LLM-Based Chunking (Simulated)
    print("\n[CHECK 9] Verifying LLM-Based Chunking (Simulated mode)...")
    payload = {
        "text": sample_text,
        "model": "openai/gpt-oss-120b",
        "simulated": True
    }
    res = client.post("/chunk/llm", json=payload)
    assert res.status_code == 200, f"LLM chunker failed: {res.status_code}"
    chunks = res.json()["chunks"]
    assert len(chunks) > 0
    assert "reason" in chunks[0], "LLM chunk boundary split reason is missing"
    print(f" -> PASSED: LLM chunking completed. Split count: {len(chunks)}")

    # 10. Agentic Chunking (LangGraph)
    print("\n[CHECK 10] Verifying Agentic Chunking (LangGraph Flow)...")
    payload = {
        "text": sample_text,
        "query": "What is the policy for sick leave?"
    }
    res = client.post("/chunk/agentic", json=payload)
    assert res.status_code == 200, f"Agentic chunker failed: {res.status_code}"
    res_data = res.json()
    assert "selected_strategy" in res_data
    assert "steps" in res_data
    assert len(res_data["steps"]) >= 4, "Should trace at least 4 nodes (Classifier, Decision, Chunking, Evaluation)"
    print(f" -> Chosen Strategy: {res_data['selected_strategy']}")
    print(f" -> Flow steps traced:")
    for step in res_data["steps"]:
        print(f"    * {step}")
    print(" -> PASSED: Agentic chunking pipeline completed and traced successfully!")

    # 11. Chunk Comparison Dashboard
    print("\n[CHECK 11] Verifying Chunk Comparison Dashboard Batch calculation...")
    res = client.post("/chunk/compare", json={"text": sample_text})
    assert res.status_code == 200, f"Compare dashboard failed: {res.status_code}"
    comparison = res.json()
    for strat in ["fixed", "recursive", "document", "semantic", "query", "metadata", "llm"]:
        assert strat in comparison, f"Missing strategy {strat} in comparison results"
        assert "coherence" in comparison[strat]
        assert "retrieval_relevance" in comparison[strat]
        assert "latency_ms" in comparison[strat]
    print(" -> PASSED: Batch comparison calculated metrics for all 7 base strategies.")

    # 12. Retrieval Simulation
    print("\n[CHECK 12] Verifying Global Retrieval Simulation...")
    # Standard query search retrieval
    chunks_payload = [
        {"index": 1, "text": "Annual leave details request advance", "metadata": {"Department": "HR"}},
        {"index": 2, "text": "Sick leave requires medical certificate", "metadata": {"Department": "HR"}}
    ]
    payload = {
        "query": "requesting medical leave",
        "chunks": chunks_payload,
        "top_k": 2
    }
    res = client.post("/chunk/retrieve", json=payload)
    assert res.status_code == 200, f"Retrieval simulator failed: {res.status_code}"
    retrieval = res.json()
    assert "retrieved" in retrieval
    assert "mean_similarity" in retrieval
    assert "precision" in retrieval
    assert "recall" in retrieval
    print(f" -> Standard Mean Similarity: {retrieval['mean_similarity']:.4f}")
    
    # Metadata-boosted retrieval
    res_meta = client.post("/chunk/metadata/retrieve", json=payload)
    assert res_meta.status_code == 200, f"Metadata-boosted retrieval failed: {res_meta.status_code}"
    retrieval_meta = res_meta.json()
    assert len(retrieval_meta["retrieved"]) > 0
    top_boosted_conf = retrieval_meta["retrieved"][0]["retrieval_confidence"]
    print(f" -> Boosted Top Match Confidence: {top_boosted_conf:.4f}")
    print(" -> PASSED: Retrieval simulation with metadata boosting verified.")

    # 13. Session Workspace Persistence
    print("\n[CHECK 13] Verifying JSON Workspace Session Persistence...")
    # Load session state (should contain data after our operations above saved chunks/stats/metadata)
    res_load = client.get("/session/load")
    assert res_load.status_code == 200
    state = res_load.json()
    assert state["metadata"] is not None or state["chunks"] is not None, "Session storage should contain progress"
    print(" -> Session loaded successfully. Keys found:", [k for k, v in state.items() if v is not None])
    
    # Clear session state
    res_clear = client.post("/session/clear")
    assert res_clear.status_code == 200
    assert res_clear.json()["status"] == "success"
    
    # Verify it is empty now
    res_load_empty = client.get("/session/load")
    assert res_load_empty.status_code == 200
    empty_state = res_load_empty.json()
    assert empty_state["metadata"] is None
    assert empty_state["chunks"] is None
    assert empty_state["stats"] is None
    assert empty_state["retrieval"] is None
    print(" -> Session cleared successfully. Workspace reset!")

    # 14. Error Handling Checks
    print("\n[CHECK 14] Verifying Error Handling & Boundary cases...")
    # Invalid overlap size (overlap >= chunk_size)
    res_bad = client.post("/chunk/fixed", json={"text": sample_text, "chunk_size": 50, "chunk_overlap": 50})
    assert res_bad.status_code == 400
    print(" -> Correctly rejected bad overlap parameters with 400 Bad Request.")
    
    # Missing required body fields (FastAPI validation)
    res_bad2 = client.post("/chunk/fixed", json={"text": sample_text})
    assert res_bad2.status_code == 422
    print(" -> Correctly rejected incomplete payloads with 422 Unprocessable Entity.")

    print("\n" + "="*50)
    print("ALL DEMO READINESS BACKEND ENDPOINTS AND LOGIC PASSED SUCCESSFULLY!")
    print("="*50)

if __name__ == "__main__":
    try:
        test_demo_readiness()
    except AssertionError as e:
        print(f"\n[FAIL] E2E Verification failed: {str(e)}")
        sys.exit(1)
    except Exception as e:
        print(f"\n[ERROR] Unexpected error during verification: {str(e)}")
        sys.exit(1)
